blank_issues_enabled: false
contact_links:
  - name: KSoft.Si Support
    url: mailto:support@ksoft.si
    about: Please ask important questions here.
  - name: Discord Server
    url: https://discord.gg/7bqdQd4
    about: Join our community!
